[package]
name = "shtml"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shtml"
path = "src/cli/main.rs"

[dependencies]
notify = "6.1"
clap = { version = "4.5", features = ["derive"] }
lazy_static = "1.4"
crossterm = "0.27"
ratatui = "0.26"
chrono = "0.4"
qrcode = "0.14"
